---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php packages for Ubuntu servers
    apt:                                       #"package" would be any of the module manager depending on the server system
      name:                                    #like CentOS,Ubuntu... 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php for CentOS servers
    dnf:                                       #package would be any of the module manager depending on the server system
      name:                                    #like CentOS,Ubuntu...
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
