---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php packages
    package:                                   #package would be any of the module manager depending on the server system
      name:                                    #like CentOS,Ubuntu... 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
